name: Build and Deploy AWS sample app

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      force_overwrite_assets:
        description: 'Force overwrite assets'
        required: false
        default: 'false'

jobs:
  run:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          node-version: '20.10.0'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm run build

      - name: Configure AWS Access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_BUCKET_REGION }}

      - id: sync-to-s3
        name: Sync new website to s3
        run: aws s3 sync dist s3://${{ secrets.S3_BUCKET }}/ --delete
        shell: bash

      - id: invalidate-cloudfront
        name: Clear CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths /
        shell: bash
